FROM python:3.6.5

LABEL io.openshift.s2i.scripts-url="image:///s2i/bin"

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

RUN mkdir microservice
WORKDIR /microservice

COPY _python /microservice

RUN pip install -U pip && \
    pip install setuptools==41.0.0

RUN cd /microservice/python && \
    make install

COPY ./s2i/bin/ /s2i/bin

EXPOSE 5000
